language: php

sudo: false

cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/.npm

branches:
  except:
  - trunk
  - assets

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  # - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.2
  global:
    BROWSERSTACK_USER: thomaslevy1
    BROWSERSTACK_KEY:
      secure: cTKpHlJRfJAFIjIdZCslWcNrjR18WJnezvsMH1ycM5ZY6oMMs7lmavMh2Ii7flo5CO5LCjvhqHp9c4+9YDmTsvNfGXz0pZuDrX6BAL8TqinX+HGNIm+9Rx2Hhnzl+MErM43St59pt+SyS2MtvUXny99xZyKkhS2KTXpcrcNkn1vWt8gCsETm1scYs1Qn5Tx+gAGBEXY69f7jR84sETCcUdsXVhqL9ob7Co84FLOwipG4JjyfaYXoEy5jf08eA9Wanp2Oj0aiVwmG3AkU1TYqBfchI6Zf/IOEyoMTowSS41stgaXCqWRfgKsyoWnk0bC2PlbVali6G3E2X27nlXgR+0v1ysErjfujzh6XGoOwJG6GjLnRcRaAvNhg2TbobYH+kv8CmiWFnN2+H9F8gHRId9d+uCib9pnpmlggMJief/1/RzzqL/6YnI5iBvOdnBdf0VG4fQvLf+2QllwRYd9oX0fHx7QGfwYYWZfaWT8IiZ5X37DhpPzYDdM3G6oFFECPMzsogrPL+QFtsDraioHJey4aGkpgIYNXi3Y8zvV1xq7oWXSE6b441QTUmeD8j4pci9HgwOw3iAE3ZkTpGVSkjE4ohLwJ6Q8x7grb0hNbI+V6rWBFz+kj0sOyOWsSk3kkdUyAI3tYgMY7m4m761l6F611dRNeI5+QMrjnPqEEv9Y=


before_script:
  - bash tests/bin/install.sh lifterlms_tests root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - bash tests/bin/travis.sh during

after_success:
  - if [[ ${TRAVIS_PHP_VERSION} == ${PHP_LATEST_STABLE} ]]; then vendor/bin/test-reporter; fi

notifications:
  slack:
    secure: xhRdeZcRwIvVqcI/tn3Npm8N83SvPkjbpK1wY3x1epi854SGtCd6iZGjKjIZUQ7fl0XnUhjOg23b45ukYZSmm5ktn/hsdrFSzPlFRZo6RQomObq/TZA9Vq8uAL5WiCKz5g+BmWt3kVRiQZvpRMU0VdzmA42jNvWxvgle8g04klxgp3IduAMzo8MOL2ubpF9k8ebEZ/TdeqVb8onUrUdOBP+Xtbu/l7cVPKW4yRGHpikOMrwfL0OTGOhETcBsF6QiCLhifKCXtqXAc2vFRIg6j7/xOx8Kd9ZVkYPAGKbN56Omu8Ejw/RWVrKlC5WUoqjKS5DUQHuBBZw8rgm0PZkzOfEHRjwcQ8gLCROOqeL9LAq/YYNW2PgbOP9NWPyDij2rX5CI8ot24hKcHMpHWw1+uXZJ5S4piOo31DhBaMlju59h+Mrn0A2A6UfBMTmzQ/LBugkn4iINgWCU2QpplqV1plDc6alwP0PXRdHflKJr5kvGsLE2KjJfKlunmXQWeZKlFO/BwG7jAEuA/aJFX+LqRlug+PXU+CBuXc6XYDLgeSiG1TT6SOIpmK2MIBz4dbsxn1F7QyGXklsm7tw78tnHAmg7qIN9r8l3Ptl1Tlmx60zY4bKm1QUW0/VbblDu/pOc5KjEuFQ/UsBGW9XyUZ7LerKhq2/f7Fn/mjK5XewHKgA=
  email: false

browserstack:
  username: thomaslevy1
  access_key:
    secure: cTKpHlJRfJAFIjIdZCslWcNrjR18WJnezvsMH1ycM5ZY6oMMs7lmavMh2Ii7flo5CO5LCjvhqHp9c4+9YDmTsvNfGXz0pZuDrX6BAL8TqinX+HGNIm+9Rx2Hhnzl+MErM43St59pt+SyS2MtvUXny99xZyKkhS2KTXpcrcNkn1vWt8gCsETm1scYs1Qn5Tx+gAGBEXY69f7jR84sETCcUdsXVhqL9ob7Co84FLOwipG4JjyfaYXoEy5jf08eA9Wanp2Oj0aiVwmG3AkU1TYqBfchI6Zf/IOEyoMTowSS41stgaXCqWRfgKsyoWnk0bC2PlbVali6G3E2X27nlXgR+0v1ysErjfujzh6XGoOwJG6GjLnRcRaAvNhg2TbobYH+kv8CmiWFnN2+H9F8gHRId9d+uCib9pnpmlggMJief/1/RzzqL/6YnI5iBvOdnBdf0VG4fQvLf+2QllwRYd9oX0fHx7QGfwYYWZfaWT8IiZ5X37DhpPzYDdM3G6oFFECPMzsogrPL+QFtsDraioHJey4aGkpgIYNXi3Y8zvV1xq7oWXSE6b441QTUmeD8j4pci9HgwOw3iAE3ZkTpGVSkjE4ohLwJ6Q8x7grb0hNbI+V6rWBFz+kj0sOyOWsSk3kkdUyAI3tYgMY7m4m761l6F611dRNeI5+QMrjnPqEEv9Y=
